# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-08 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180408_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myunit',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='myunit',
            name='user',
        ),
        migrations.AddField(
            model_name='myunit',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
