# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-08 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180408_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myunit',
            name='name',
        ),
    ]
